
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(20) NOT NULL,
  password TEXT NOT NULL,

  UNIQUE(username)
);

CREATE TABLE IF NOT EXISTS urls (
  id INTEGER  PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  short_url TEXT NOT NULL,

  UNIQUE(short_url)
);
